spring.datasource.url=jdbc:postgresql://localhost:5432/dfd_builder
spring.datasource.username=postgres
spring.datasource.password=Ganesh@24

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true